# .readthedocs.yaml
# Configuration Read the Docs v2
# https://docs.readthedocs.io/en/stable/config-file/v2.html

version: 2

sphinx:
  configuration: doc/source/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: doc/requirements.txt
