services:
  web:
    image: ${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:v${VERSION}
    env_file: .env
    environment:
      # on redéclare explicitement ce qui compte en prod
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT}
      PORT: ${PORT}
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        gunicorn oc_lettings_site.wsgi:application
          -b 0.0.0.0:8000
          --workers ${GUNICORN_WORKERS:-3}
          --timeout ${GUNICORN_TIMEOUT:-60}
      "