version: "3.9"

services:
  web:
    image: "${DOCKERHUB_USER}/${DOCKERHUB_IMAGE}:v${VERSION}"
    container_name: oc_lettings_web
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: ${DJANGO_SETTINGS_MODULE}
      GUNICORN_WORKERS: ${GUNICORN_WORKERS:-3}
      GUNICORN_TIMEOUT: ${GUNICORN_TIMEOUT:-60}
      PORT: ${PORT:-8000}
    ports:
      - "${PORT:-8000}:8000"
    restart: unless-stopped
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py collectstatic --noinput &&
        exec gunicorn oc_lettings_site.wsgi:application
          -b 0.0.0.0:${PORT:-8000}
          --workers ${GUNICORN_WORKERS:-3}
          --timeout ${GUNICORN_TIMEOUT:-60}
      "
    volumes:
      - static_data:/app/staticfiles
      - media_data:/app/media

volumes:
  static_data:
  media_data: