name: Build & Push Docker

on:
  push:
    tags:
      - 'v*'                 # démarre dès qu’un tag v1, v1.2, v1.2.3 est poussé
  release:
    types: [published]       # démarre quand une Release GitHub est publiée
  workflow_dispatch: {}      # bouton "Run workflow" pour tester

jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_IMAGE: oc-lettings-site
      # si déclenché par tag => ref_name (v1.3), sinon par release => tag_name
      TAG: ${{ github.ref_type == 'tag' && github.ref_name || github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & Push
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_IMAGE }}:${{ env.TAG }}
            ${{ env.DOCKERHUB_USER }}/${{ env.DOCKERHUB_IMAGE }}:latest
          labels: |
            org.opencontainers.image.version=${{ env.TAG }}
            org.opencontainers.image.source=${{ github.repository }}
            org.opencontainers.image.revision=${{ github.sha }}