name: Release Please

on:
  push:
    branches: [ main ]   # déclenché quand main reçoit de nouveaux commits

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: Release Please
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          target-branch: main